name: dart1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  postgres: ^3.2.1
  shelf: ^1.4.2
  shelf_router: any
  
dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.24.0
